Add new cuda version (#102)
* compact Dockerfile
* optimize install script
* update cuda pkgs
* fix sys py3

diff --git a/docker_base/Dockerfile b/docker_base/Dockerfile
--- a/docker_base/Dockerfile
+++ b/docker_base/Dockerfile
@@ -9,30 +9,32 @@ ARG PYTHON_VERSION="3.12"
 
 ENV CONDA_PREFIX=/opt/conda
 
-RUN set -x && source /opt/utils/script-setup.sh && source /opt/utils/script-setup-sys.sh \
+RUN set -eux && source /opt/utils/script-setup.sh && source /opt/utils/script-setup-sys.sh \
  && export PATH=$PATH:${CONDA_PREFIX}/bin \
  && install_apt /opt/utils/install_list_base.apt \
  && echo "Install tini:" && setup_tini \
- && export HAS_SYS_PY3=$( [ -x "$(command -v python3)" ] && echo 'true' || echo 'false' ) && echo "@ Detect OS Py3 installed: $HAS_SYS_PY3" \
+ && export HAS_SYS_PY3=$( [ -x "$(command -v python3)" ] && echo 'true' || echo 'false' ) && echo "@ Detect OS Py3 installed: ${HAS_SYS_PY3:-error}" \
  && echo "Install Mamba:" && setup_mamba \
  && echo "Install Python ${PYTHON_VERSION} and conda:" && setup_conda_with_mamba ${PYTHON_VERSION} \
  && echo "Backup the conda version of platform.py as it's different from the system version." \
  && cp "${CONDA_PREFIX}/lib/python${PYTHON_VERSION}"/platform.py "${CONDA_PREFIX}/lib/python${PYTHON_VERSION}"/platform.py.bak \
- && $($HAS_SYS_PY3) && ( \
-       echo "Replace system Python3 with conda Python - note that /bin and /sbin are symlinks of /usr/bin in docker image ubuntu" \
+ && if $(${HAS_SYS_PY3:-false}) ; then \
+       py3versions -d \
     && PYTHON_VERSION_DEFAULT=$(py3versions -v -i) \
-    && sed -i "s/${PYTHON_VERSION_DEFAULT}/${PYTHON_VERSION}/g" /usr/share/python3/debian_defaults \
     && PYTHON_PTH_FILE=$("${CONDA_PREFIX}"/bin/python3 -c 'import sys;print(sys.path[-1]+"/usr_share.pth")') \
+    && echo "Found default system python3 version: ${PYTHON_VERSION_DEFAULT}" \
+    && echo "Replace system Python3 with conda Python - note that /bin and /sbin are symlinks of /usr/bin in docker image ubuntu" \
+    && sed -i "s/${PYTHON_VERSION_DEFAULT}/${PYTHON_VERSION}/g" /usr/share/python3/debian_defaults \
     && echo "/usr/share/pyshared/" >>  "${PYTHON_PTH_FILE}" \
     && echo "/usr/share/python3/"  >>  "${PYTHON_PTH_FILE}" \
     && rm -rf $(/usr/bin/python3 -c 'import sys; print(" ".join(i for i in sys.path if "python" in i))') /usr/bin/python3* /usr/lib/python${PYTHON_VERSION} \
- ) || true \
- && ln -sf "${CONDA_PREFIX}"/lib/python${PYTHON_VERSION} /usr/lib/ \
+    && rm -rf /usr/lib/python${PYTHON_VERSION} && ln -sf "${CONDA_PREFIX}"/lib/python${PYTHON_VERSION} /usr/lib/ ; \
+ else \
+     echo "No default python found in OS." ; \
+ fi \
  && ln -sf "${CONDA_PREFIX}"/bin/python3.* /usr/bin/ \
  && ln -sf "/usr/bin/python${PYTHON_VERSION}" /usr/bin/python  \
  && ln -sf "/usr/bin/python${PYTHON_VERSION}" /usr/bin/python3 \
- && ls -alh /usr/bin/python* \
- && $($HAS_SYS_PY3) && ( py3versions -d ) || true \
  && lsb_release -a \
- && which python && python --version \
+ && which python && python --version && ls -alh /usr/bin/python* \
  && install__clean && fix_permission 0 /opt
