compact Dockerfile

diff --git a/docker_core/Dockerfile b/docker_core/Dockerfile
--- a/docker_core/Dockerfile
+++ b/docker_core/Dockerfile
@@ -8,57 +8,55 @@ LABEL maintainer="haobibo@gmail.com"
 
 ARG ARG_PROFILE_NODEJS
 
-ARG ARG_PROFILE_JAVA
-
 # base,datascience,rstudio,rshiny
 ARG ARG_PROFILE_R
 
 # base,database,datascience,nlp,cv,bioinfo
 ARG ARG_PROFILE_PYTHON
-
 ARG ARG_PROFILE_GO
-
 ARG ARG_PROFILE_JULIA
-
 ARG ARG_PROFILE_RUST
-
 ARG ARG_PROFILE_OCTAVE
 
 # base,cjk
 ARG ARG_PROFILE_LATEX
 
+ARG ARG_PROFILE_JAVA
+ARG VERSION_JDK
+
 COPY work /opt/utils/
 
-# NodeJS is required to build JupyterLab Extensions later
-RUN $(grep -q "base" <<< "${ARG_PROFILE_NODEJS}") && ( \
-      source /opt/utils/script-setup.sh && setup_node && install__clean \
-    ) || echo "Skip NodeJS install"
-
-# If installing Java environment - notice that Java can be dependency for some other packages like rJava
-ARG VERSION_JDK
-RUN source /opt/utils/script-setup.sh \
+RUN set -eux && source /opt/utils/script-setup.sh\
+ # -----------------------------
+ # NodeJS is required to build JupyterLab Extensions later
+ && if echo "${ARG_PROFILE_NODEJS}" | grep -q "base" ; then \
+      setup_node ; \
+    else \
+      echo "Skip NodeJS install" ; \
+    fi \
+ # -----------------------------
+ # If installing Java environment - notice that Java can be dependency for some other packages like rJava
  && export VERSION_JDK=${VERSION_JDK:-11} \
- && for profile in $(echo $ARG_PROFILE_JAVA | tr "," "\n") ; do ( setup_java_${profile} ) ; done
-
-# If installing LaTex and LaTex CJK packages.
-RUN source /opt/utils/script-utils.sh \
- && for profile in $(echo $ARG_PROFILE_LATEX | tr "," "\n") ; do ( install_apt "/opt/utils/install_list_latex_${profile}.apt" ) ; done
-
-# If installing R environment - put this after Java ready to configure rJava
-RUN source /opt/utils/script-setup-R.sh \
- && for profile in $(echo $ARG_PROFILE_R | tr "," "\n") ; do ( setup_R_${profile} ) ; done
-
-# If on a x86_64 architecture: 1) if mkl specified, install nomkl; 2) install conda packages as specified.
-RUN $(grep -q "x86_64" <<< `arch`) && ( \
-      ( $(grep -q "mkl" <<< "${ARG_PROFILE_PYTHON}") && \
-        ( echo "mkl"   >> /opt/utils/install_list_core.conda && echo "Install mkl.") || \
-        ( echo "nomkl" >> /opt/utils/install_list_core.conda && echo "Install nomkl.") \
-      ) \
-    ) \
- && source /opt/utils/script-utils.sh && install_conda /opt/utils/install_list_core.conda && install__clean
-
-# If installing Python packages
-RUN source /opt/utils/script-utils.sh \
+ && for profile in $(echo $ARG_PROFILE_JAVA | tr "," "\n") ; do ( setup_java_${profile} ) ; done \
+ # -----------------------------
+ # If installing LaTex and LaTex CJK packages.
+ && source /opt/utils/script-utils.sh \
+ && for profile in $(echo $ARG_PROFILE_LATEX | tr "," "\n") ; do ( install_apt "/opt/utils/install_list_latex_${profile}.apt" ) ; done \
+ # -----------------------------
+ # If installing R environment - put this after Java ready to configure rJava
+ && source /opt/utils/script-setup-R.sh \
+ && for profile in $(echo $ARG_PROFILE_R | tr "," "\n") ; do ( setup_R_${profile} ) ; done \
+ # -----------------------------
+ # If on a x86_64 architecture: 1) if mkl specified, install nomkl; 2) install conda packages as specified.
+ if echo $(arch) | grep -q "x86_64" ; then \
+    echo "mkl"   >> /opt/utils/install_list_core.conda && echo "Install mkl." ; \
+  else \
+    echo "nomkl" >> /opt/utils/install_list_core.conda && echo "Install nomkl." ; \
+  fi \
+  && source /opt/utils/script-utils.sh && install_conda /opt/utils/install_list_core.conda \
+ # -----------------------------
+ # If installing Python packages
+ && source /opt/utils/script-utils.sh \
  && ( $(grep -q "datascience" <<< "${ARG_PROFILE_PYTHON}") && ( \
          ( which R     && echo "rpy2  % Install rpy2 if R exists"    >> /opt/utils/install_list_PY_datascience.pip || echo "Skip rpy2 install" ) \
       && ( which java  && echo "py4j  % Install py4j if Java exists" >> /opt/utils/install_list_PY_datascience.pip || echo "Skip py4j install" ) \
@@ -87,16 +85,30 @@ RUN source /opt/utils/script-utils.sh \
       && V=$(echo ${PADDLE}==${PADDLE_VER}) && echo "to install paddle: ${V}" \
       && pip install ${V} -f "https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html" \
     ) || echo "Skip paddle install" ) \
-  && install__clean
-
-
-RUN $(grep -q "base" <<< "${ARG_PROFILE_GO}")     && ( source /opt/utils/script-setup.sh && setup_GO     ) || echo "Skip go install"
-
-RUN $(grep -q "base" <<< "${ARG_PROFILE_RUST}")   && ( source /opt/utils/script-setup.sh && setup_rust   ) || echo "Skip rust install"
-
-RUN $(grep -q "base" <<< "${ARG_PROFILE_JULIA}")  && ( source /opt/utils/script-setup.sh && setup_julia  ) || echo "Skip julia install"
-
-RUN $(grep -q "base" <<< "${ARG_PROFILE_OCTAVE}") && ( source /opt/utils/script-setup.sh && setup_octave ) || echo "Skip octave install"
-
-# Clean up and display components version information...
-RUN source /opt/utils/script-utils.sh && list_installed_packages && install__clean
+ # -----------------------------
+ && if echo "${ARG_PROFILE_GO}" | grep -q "base" ; then \
+       echo "Installing GO: ${ARG_PROFILE_GO}" && setup_GO ;
+    else \
+       echo "Skip installing GO" ;
+    fi \
+ # -----------------------------
+ && if echo "${ARG_PROFILE_RUST}" | grep -q "base" ; then \
+       echo "Installing rust: ${ARG_PROFILE_RUST}" && setup_rust ;
+    else \
+       echo "Skip installing rust" ;
+    fi \
+ # -----------------------------
+ && if echo "${ARG_PROFILE_JULIA}" | grep -q "base" ; then \
+       echo "Installing julia: ${ARG_PROFILE_JULIA}" && setup_julia ;
+    else \
+       echo "Skip installing julia" ;
+    fi \
+ # -----------------------------
+ && if echo "${ARG_PROFILE_OCTAVE}" | grep -q "base" ; then \
+       echo "Installing Octave: ${ARG_PROFILE_OCTAVE}" && setup_octave ;
+    else \
+       echo "Skip installing octave" ;
+    fi \
+ # -----------------------------
+ # Clean up and display components version information...
+ && source /opt/utils/script-utils.sh && list_installed_packages && install__clean
