update devtools (#85)

diff --git a/docker_dev/Dockerfile b/docker_dev/Dockerfile
--- a/docker_dev/Dockerfile
+++ b/docker_dev/Dockerfile
@@ -18,7 +18,7 @@ COPY work /opt/utils/
 
 # Setup Jupyter: Basic Configurations and Extensions...
 RUN mkdir -pv /opt/conda/etc/jupyter/ \
- && mv /opt/utils/jupyter_notebook_config.json /opt/conda/etc/jupyter/ \
+ && mv /opt/utils/etc_jupyter/* /opt/conda/etc/jupyter/ && rm -rf /opt/utils/etc_jupyter \
  && mv /opt/utils/start-*.sh /usr/local/bin/ && chmod +x /usr/local/bin/start-*.sh \
  && source /opt/utils/script-extend.sh \
  && for profile in $(echo $ARG_PROFILE_JUPYTER | tr "," "\n") ; do ( setup_jupyter_${profile} || true ) ; done
@@ -31,10 +31,18 @@ RUN source /opt/utils/script-extend.sh \
  && for profile in $(echo $ARG_PROFILE_VSCODE | tr "," "\n") ; do ( setup_vscode_${profile} || true ) ; done
 
 # Clean up and display components version information...
-RUN source /opt/utils/script-utils.sh  && install__clean
+RUN source /opt/utils/script-utils.sh && install__clean && list_installed_packages
 
 WORKDIR $HOME_DIR
 EXPOSE 8888
 
 ENTRYPOINT ["tini", "-g", "--"]
 CMD ["start-notebook.sh"]
+
+# '-c' option make bash commands are read from string.
+#   If there are arguments after the string, they are assigned to the positional parameters, starting with $0.
+# '-o pipefail'  prevents errors in a pipeline from being masked.
+#   If any command in a pipeline fails, that return code will be used as the return code of the whole pipeline.
+# '--login': make bash first reads and executes commands from  the file /etc/profile, if that file exists.
+#   After that, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable.
+SHELL ["/bin/bash", "--login", "-o", "pipefail", "-c"]
